name: charts_common
version: 0.13.3
description: A common library for charting packages.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  intl: ^0.20.2
  logging: ^1.3.0
  meta: ^1.16.0
  vector_math: ^2.1.4
