name: charts_common
version: 0.12.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  collection: ^1.8.0
  intl: "0.18.1"
  logging: ^1.2.0
  meta: ^1.9.1
  vector_math: ^2.0.8

dev_dependencies:
  mockito: ^5.0.0
  test: ^1.5.3
